[task_02] Add task 02
brstu/GIIS-2024 pull request #27
Opened 2024-02-27 11:50 UTC by Corowka

2024-02-28 05:29 UTC, NogameNo-life requested changes
переименуйте каталог с номером на "ii02208"

2024-03-03 18:08 UTC, neonchikCallMe approved these changes
Код хороший, визуал красивый, всё баги гитхабовские исправил. Одобряю

2024-03-05 05:12 UTC, NogameNo-life commented
> Код хороший, визуал красивый, всё баги гитхабовские исправил. Одобряю

А я не одобряю)

2024-03-05 05:47 UTC, Corowka commented
> > Код хороший, визуал красивый, всё баги гитхабовские исправил. Одобряю
> 
> А я не одобряю)

>
> А подскажите, пожалуйста, что не так? Кто жук, кто инвалид?

2024-03-05 05:48 UTC, Corowka commented
> А я не одобряю)

>
> А подскажите, пожалуйста, что не так? Кто жук, кто инвалид?

2024-03-05 05:49 UTC, Corowka commented
> А я не одобряю)
А подскажите, пожалуйста, что не так? Кто жук, кто инвалид?

2024-03-05 09:52 UTC, psijikk approved these changes
Xarow!

2024-03-12 05:12 UTC, NogameNo-life approved these changes

2024-03-12 05:12 UTC, merged