[task_02] add task 02
brstu/GIIS-2024 pull request #28
Opened 2024-02-27 12:04 UTC by neonchikCallMe

2024-02-29 06:17 UTC, Adryian4ik approved these changes
Код выглядит хорошо :+1: . Чужие файлы не меняет, добавляется только своя 2 лаба.  SonarCloud ругается только на файлы из папки другого человека.

2024-03-05 05:33 UTC, NogameNo-life requested changes

2024-03-05 05:33 UTC, NogameNo-life commented on trunk/ii02210/task_02/src/CMakeLists.txt
> +
set(CMAKE_PREFIX_PATH $ENV{QTDIR})

2024-03-05 10:48 UTC, NogameNo-life approved these changes

2024-03-05 10:49 UTC, merged