[task_03] Add task 03
brstu/GIIS-2024 pull request #32
Opened 2024-03-12 08:39 UTC by Corowka

2024-03-12 12:22 UTC, Adryian4ik commented on README.md
> +| 8   | [Копанчук Евгений](https://github.com/orgs/brstu/people/Corowka)        |[II2208](./trunk/II2208) |:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|     |     |     |     |         |
Удален рейтинг в таблице, просьба его вернуть)

2024-03-12 12:45 UTC, Corowka commented on README.md
> +| 8   | [Копанчук Евгений](https://github.com/orgs/brstu/people/Corowka)        |[II2208](./trunk/II2208) |:heavy_check_mark:|:heavy_check_mark:|:heavy_check_mark:|     |     |     |     |         |
Спасибо, я нашел потеряшку и вернул в семью

2024-03-12 12:46 UTC, neonchikCallMe approved these changes
теперь точно хорошо. сайтик очень красивый, нужно отправить его оджибуде иначе лабу не зачтут....

2024-03-12 12:55 UTC, Adryian4ik approved these changes
All good :+1:

2024-03-19 05:44 UTC, NogameNo-life requested changes

2024-03-19 05:44 UTC, NogameNo-life commented on trunk/ii02208/task_03/readme.md
> +## Лабораторная работа №3
Заголовок первого уровня

2024-03-19 05:44 UTC, NogameNo-life commented on trunk/ii02208/task_03/readme.md
> +### Код программы
Зачем код целиком вставлять? Code Duplication только выше от этого.

2024-04-02 08:17 UTC, closed without merging